; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = tab5
data_dir = data

[env:tab5]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
framework = arduino
board = esp32-p4-evboard
board_build.mcu = esp32p4
board_build.flash_mode = qio
board_build.filesystem = littlefs
board_build.partitions = partitions.csv
upload_speed = 1500000
monitor_speed = 115200
lib_deps = 
	m5stack/M5Unified
	m5stack/M5GFX
	m5stack/M5Unit-KEYBOARD
	bblanchon/ArduinoJson@^7.4.3
	ewpa/LibSSH-ESP32@^5.8.0
build_flags = 
	-DBOARD_HAS_PSRAM
	-DARDUINO_USB_CDC_ON_BOOT=1
	-DARDUINO_USB_MODE=1
	-DUSE_M5_TAB5_KEYBOARD=1
	-DENABLE_USB_HOST_KEYBOARD=1
	-DENABLE_BLE_HID_KEYBOARD=1
	-DCONFIG_ESP_HOSTED_ENABLE_BT_NIMBLE=1
	-DCONFIG_NIMBLE_ENABLED=1
	-DENABLE_SSH=1
	-DARDUINO_LOOP_STACK_SIZE=32768
	-Wall
